{{ if not (empty .Values.envSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
{{- range $key, $val := .Values.envSecrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end -}}